/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTEND;

import DATA.clsQuerys;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import BACKEND.clsClientes;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author geovanni
 */
public class frmCliente extends javax.swing.JFrame {

    /**
     * Creates new form frmCliente
     */
    public frmCliente() {
        initComponents();
        Limpiar();
        ctId.setVisible(false);
    }
   
    private void Limpiar(){
        ctNombre.setText("");
        ctNit.setText("");
        ctDireccion.setText("");
        ctId.setText("");
        CargarPersonas();
    }
    private void CargarPersonas(){
        
        DefaultTableModel modeloTabla =  (DefaultTableModel)tbPersonas.getModel();
        modeloTabla.setRowCount(0); //ELIMINO FILAS
        ResultSet rs;  //BD
        ResultSetMetaData rsmd;  // TABLA
        int Columnas;
        try{
                    
            clsQuerys objBD = new clsQuerys();
            rs = objBD.fncConsultaCliente(0);
            rsmd = rs.getMetaData();
            Columnas = rsmd.getColumnCount();
            
            while(rs.next()){
                Object[] fila = new Object[Columnas];
                for(int indice = 0; indice < Columnas; indice ++){
                    fila[indice] = rs.getObject(indice + 1 );
                }
                modeloTabla.addRow(fila);
                
            }
                    
                    
        }catch(SQLException e){
            System.out.println(e.toString());
        }
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbPersonas = new javax.swing.JTable();
        ctNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ctNit = new javax.swing.JTextField();
        ctDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ctId = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "DIRECCION", "NIT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPersonasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPersonas);

        ctNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ctNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctNombreActionPerformed(evt);
            }
        });

        jLabel3.setText("NOMBRE:");

        jLabel4.setText("NIT");

        ctNit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ctDireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ctDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctDireccionActionPerformed(evt);
            }
        });

        jLabel5.setText("DIRECCION:");

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnCrear.setText("CREAR");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        jButton1.setText("MENU");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ctNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163)
                                .addComponent(ctId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ctDireccion)
                                    .addComponent(ctNit, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
                                .addGap(108, 108, 108)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ctNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ctNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ctDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnModificar)
                    .addComponent(btnCrear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPersonasMouseClicked
        try{
            int fila = tbPersonas.getSelectedRow();
            int ID =   Integer.parseInt(  tbPersonas.getValueAt(fila, 0).toString()    )  ;
            ResultSet rs;
            clsQuerys objBD = new clsQuerys();
            rs = objBD.fncConsultaCliente(ID);

            while(rs.next()){
                ctId.setText(rs.getString("ID")    );
                ctNombre.setText( rs.getString("NOMBRE")  );
                ctNit.setText( rs.getString("NIT")  );
                ctDireccion.setText( rs.getString("DIRECCION")  );
            }
            JOptionPane.showMessageDialog(this,  String.valueOf(ID)    );
        }catch(Exception Ex){
            System.out.println( Ex.getMessage());
        }
    }//GEN-LAST:event_tbPersonasMouseClicked

    private void ctDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctDireccionActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        clsQuerys objBD = new clsQuerys();
        if(ctId.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe seleccionar un registro para eliminar");
        }else{
            if (    objBD.fncEliminaCliente(Integer.valueOf(  ctId.getText()    ) ) ==1 ){
                JOptionPane.showMessageDialog(this, "Se eliminó correctamente el registro.");
                CargarPersonas();
                Limpiar();

            }

        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        if(fncValidaFormulario()==1){
            if(ctId.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Debe seleccionar un registro para actualizar");
            }else{
                clsClientes objPersona = new clsClientes();
                objPersona.setID(Integer.valueOf(  ctId.getText()    ) );
                objPersona.setNOMBRE(  ctNombre.getText()   );
                objPersona.setNIT(Integer.valueOf(  ctNit.getText()  ) );
                objPersona.setDIRECCION(  ctDireccion.getText()   );

               

                clsQuerys objBD = new clsQuerys();  //CREA UN INSTANCIA

                if(  objBD.fncModificaCliente(objPersona)==1){
                    JOptionPane.showMessageDialog(this, "Registro fue Actualizado.");
                    CargarPersonas();
                    Limpiar();
                }else{
                    JOptionPane.showMessageDialog(this, "Registro NO Ingresado.");
                }
            }
        }
        

    }//GEN-LAST:event_btnModificarActionPerformed

    private void ctNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctNombreActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
         if(fncValidaFormulario()==1){
            clsClientes objCliente = new clsClientes();

            objCliente.setNOMBRE(  ctNombre.getText()   );
            objCliente.setDIRECCION(  ctDireccion.getText()   );
            objCliente.setNIT(Integer.valueOf( ctNit.getText()));
     
        

             clsQuerys objInsertar = new clsQuerys();  //CREA UN INSTANCIA

             if(  objInsertar.fncIngresoCliente(objCliente)==1){
                    JOptionPane.showMessageDialog(this, "PRODUCTO REGISTRADO.");
                     CargarPersonas();
                     Limpiar();
                    
             }else{
                    JOptionPane.showMessageDialog(this, "PRODUCTO NO REGISTRADO.");   
             }
            }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frmInicio fi = new frmInicio();
        fi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
      
    private int fncValidaFormulario(){
        int Resp =0;
        if( ctNombre.getText().equals("") ){
                  JOptionPane.showMessageDialog(this, "Debe ingresar el nombre de la persona.");
        }else{
            if(ctNit.getText().equals("")){
                 JOptionPane.showMessageDialog(this, "Debe ingresar el nit de la persona.");
            }else{
                 if (ctDireccion.getText().equals("")){
                      JOptionPane.showMessageDialog(this, "Debe ingresar la direccion de la persona.");
                 }else{
                     Resp =1;
                 } 
            }
        }
        
        return Resp;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JTextField ctDireccion;
    private javax.swing.JTextField ctId;
    private javax.swing.JTextField ctNit;
    private javax.swing.JTextField ctNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPersonas;
    // End of variables declaration//GEN-END:variables
}
