/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FRONTEND;

import BACKEND.clsProducto;
import DATA.clsQuerys;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class frmInventario extends javax.swing.JFrame {

    /**
     * Creates new form frmInventario
     */
    public frmInventario() {
        initComponents();
        CargarProductos();
        ctEstado.setVisible(false);
        ctCOD_PRODUTO.setVisible(false);
        lbExistente.setVisible(false);
        lbInexistente.setVisible(false);   
    }
    
    public void Limpiar(){
    ctNombre.setText("");
    ctDescripcion.setText("");
    ctCantidad.setText("");
    ctPrecio.setText("");
    lbExistente.setVisible(false);
    lbInexistente.setVisible(false);   
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ctNombre = new javax.swing.JTextField();
        ctDescripcion = new javax.swing.JTextField();
        ctCantidad = new javax.swing.JTextField();
        ctPrecio = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        lbEstatus = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbInventario = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();
        lbExistente = new javax.swing.JLabel();
        ctEstado = new javax.swing.JTextField();
        lbInexistente = new javax.swing.JLabel();
        ctCOD_PRODUTO = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setType(java.awt.Window.Type.UTILITY);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setText("NOMBRE:");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("DESCRIPCION:");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setText("CANTIDAD:");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setText("PRECIO:");

        ctNombre.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        ctDescripcion.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        ctCantidad.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N

        ctPrecio.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        ctPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctPrecioActionPerformed(evt);
            }
        });

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Imagen1.png"))); // NOI18N
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        lbEstatus.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        lbEstatus.setText("S");

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FARMACIA UMG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Imagen3.png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(java.awt.Color.white);
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Imagen2.png"))); // NOI18N
        btnEliminar.setBorder(null);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 27, Short.MAX_VALUE)
        );

        tbInventario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tbInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Producto", "Descripción", "Cantidad", "Precio", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbInventarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbInventario);

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Imagen4.png"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lbExistente.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbExistente.setForeground(new java.awt.Color(0, 204, 51));
        lbExistente.setText("ESTATUS: EXISTENTE");

        ctEstado.setFont(new java.awt.Font("Century Gothic", 0, 3)); // NOI18N

        lbInexistente.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbInexistente.setForeground(new java.awt.Color(255, 51, 51));
        lbInexistente.setText("ESTATUS: INEXISTENTE");

        ctCOD_PRODUTO.setFont(new java.awt.Font("Century Gothic", 0, 3)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Imagen5.png"))); // NOI18N
        jLabel5.setText(" Inventario de Productos");

        jButton1.setText("Ventas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(30, 30, 30)
                                    .addComponent(lbEstatus)
                                    .addGap(868, 868, 868))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(112, 112, 112)
                                    .addComponent(ctEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ctCOD_PRODUTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel3)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(ctCantidad))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabel1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(ctNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(26, 26, 26)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel2)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(ctDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(ctPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(443, 443, 443))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(275, 275, 275)
                                    .addComponent(btnEliminar)
                                    .addGap(29, 29, 29)
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lbInexistente)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbExistente)))
                            .addGap(38, 38, 38))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(257, 257, 257)
                                    .addComponent(jLabel5)))
                            .addGap(48, 48, 48)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctCOD_PRODUTO, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ctNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(ctDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ctCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(ctPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbExistente)
                    .addComponent(lbInexistente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbEstatus)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ctPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctPrecioActionPerformed

     private int fncValidaFormulario(){
        int Resp =0;
        if( ctNombre.getText().equals("") ){
                  JOptionPane.showMessageDialog(this, "Debe ingresar el nombre del producto.");
              }else{

                  if(ctDescripcion.getText().equals("")){
                       JOptionPane.showMessageDialog(this, "Debe ingresar la descripcion del producto.");
                  }else{
                       if (ctCantidad.getText().equals("")){
                            JOptionPane.showMessageDialog(this, "Debe ingresar la cantidad del producto.");
                       }else{
                           if (ctPrecio.getText().equals("")){
                                JOptionPane.showMessageDialog(this, "Debe ingresar el precio del producto.");
                           }else{
                                Resp =1;
                           }
                       }        


                  }

                }
        
        return Resp;
    }

    
    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        
        if(fncValidaFormulario()==1){
             clsProducto objProducto  = new clsProducto();

             objProducto.setNombre(  ctNombre.getText()   );
             objProducto.setDescripcion(  ctDescripcion.getText()   );
            objProducto.setCantidad(Integer.valueOf( ctCantidad.getText()));
             objProducto.setPrecio( Double.valueOf(ctPrecio.getText()   ) );
     
        

             clsQuerys objInsertar = new clsQuerys();  //CREA UN INSTANCIA

             if(  objInsertar.fncIngresoProducto2(objProducto)==1){
                    JOptionPane.showMessageDialog(this, "PRODUCTO REGISTRADO.");
                     CargarProductos();
                     Limpiar();
                    
             }else{
                    JOptionPane.showMessageDialog(this, "PRODUCTO NO REGISTRADO.");   
             }
            }
        
        
        
        
    }//GEN-LAST:event_btnRegistrarActionPerformed
  
    private void CargarProductos(){
        
        DefaultTableModel modeloTabla =  (DefaultTableModel)tbInventario.getModel();
        modeloTabla.setRowCount(0); 
        
        ResultSet rs;  
        ResultSetMetaData rsmd; 
        int Columnas;
        
        
        try{
                    
            clsQuerys objBD = new clsQuerys();
            rs = objBD.fncConsultaInventario(0);
            rsmd = rs.getMetaData();
            Columnas = rsmd.getColumnCount();
            
            while(rs.next()){
                Object[] fila = new Object[Columnas];
                
                for(int indice = 0; indice < Columnas; indice ++){
                    
                    fila[indice] = rs.getObject(indice + 1 );
                }
                modeloTabla.addRow(fila);
                
            }
                    
                    
        }catch(SQLException e){
            System.out.println(e.toString());
        }
        
        
    }
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
      if(fncValidaFormulario()==1){
             clsProducto objProducto = new clsProducto();

             
            
             
            objProducto.setNombre(  ctNombre.getText()   );
            objProducto.setDescripcion(  ctDescripcion.getText()   );
             objProducto.setCantidad( Integer.valueOf(ctCantidad.getText()));
              if (Integer.valueOf(ctCantidad.getText()) < 1 ) {
              ctEstado.setText("N");
                }else{
              ctEstado.setText("S");
              }
             objProducto.setPrecio( Double.valueOf( ctPrecio.getText())    );
              objProducto.setEstatus(  ctEstado.getText()   );
               objProducto.setCOD_PRODUTO( Integer.valueOf( ctCOD_PRODUTO.getText() )  );
       
          
             clsQuerys objBD = new clsQuerys();  
                     
            if(  objBD.fncModificar(objProducto)==1){
                    JOptionPane.showMessageDialog(this, "Producto del inventario ACTUALIZADO.");
                    CargarProductos();
                    Limpiar();
                    
             }else{
                    JOptionPane.showMessageDialog(this, "Producto del inventario NO ACTUALIZADO");   
             }
            }

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        clsQuerys objBD = new clsQuerys();
         if(ctCOD_PRODUTO.getText().equals("")){
             JOptionPane.showMessageDialog(this, "Seleccione un producto a eliminar");
         }else{
              if ( objBD.fncEliminar( Integer.valueOf(  ctCOD_PRODUTO.getText()    ) ) ==1 ){
                  JOptionPane.showMessageDialog(this, "Procuto eliminado de inventario con éxito.");
                  CargarProductos();
                    Limpiar();
                  
              } 
             
         }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        Limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tbInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbInventarioMouseClicked
        try{
            int fila = tbInventario.getSelectedRow();
            int Codigo =   Integer.parseInt(  tbInventario.getValueAt(fila, 0).toString()    )  ;
            ResultSet rs;
            clsQuerys objBD = new clsQuerys();
            rs = objBD.fncConsultaInventario(Codigo);
            
            while(rs.next()){
                    ctNombre.setText( rs.getString("PRODUCTO")  );
                    ctDescripcion.setText( rs.getString("DESCRIPCION")  );
                    ctCantidad.setText( rs.getString("CANTIDAD")  );
                    ctPrecio.setText(    rs.getString("PRECIO")     );
                   ctEstado.setText(    rs.getString("ESTATUS")     );
                    ctCOD_PRODUTO.setText(  rs.getString("COD_PRODUTO")  );
                      
                   if ("S".equals(ctEstado.getText())) {
                    lbExistente.setVisible(true);
                    lbInexistente.setVisible(false);
                }else{
                   
                    lbExistente.setVisible(false);
                    lbInexistente.setVisible(true);              
                   }
              
            }
         
        }catch(Exception Ex){
            System.out.println( Ex.getMessage());
        }
    }//GEN-LAST:event_tbInventarioMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frmVenta F = new frmVenta();
        F.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JTextField ctCOD_PRODUTO;
    private javax.swing.JTextField ctCantidad;
    private javax.swing.JTextField ctDescripcion;
    private javax.swing.JTextField ctEstado;
    private javax.swing.JTextField ctNombre;
    private javax.swing.JTextField ctPrecio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbEstatus;
    private javax.swing.JLabel lbExistente;
    private javax.swing.JLabel lbInexistente;
    private javax.swing.JTable tbInventario;
    // End of variables declaration//GEN-END:variables
}
